/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db_pertanian;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rokhis
 */
public class Form_Penjualan extends javax.swing.JFrame {

    private Connection conn;
    private DefaultTableModel model;
    private ResultSet res;
    private Statement stat;
    private PreparedStatement pst;
    private int ID_Distributor, ID_Admin, kode_tanaman;
    private String tgl_transaksi;
    private int id_distributor, id_admin, kod_tanaman;

    public Form_Penjualan() {
        initComponents();

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        conn = Koneksi2.koneksi();
        model = new DefaultTableModel();
        model.addColumn("ID PENJUALAN");
        model.addColumn("KODE TANAMAN");
        model.addColumn("ID DISTRIBUTOR");
        model.addColumn("ID ADMIN");
        model.addColumn("JUMLAH");
        model.addColumn("HARGA");
        model.addColumn("TOTAL");
        model.addColumn("TGL");
        tbl_transaksi.setModel(model);

        // menampilkan data transaksi
        getDataTransaksi();
        // menampilkan data tanaman, distributor, admin pada combo box
        getMultipleData();
    }

    private void getMultipleData() {
        // data tanaman;
        try {
            String sql = "SELECT DISTINCT(Nama) as 'nama' from tb_tanaman";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            cb_tanaman.removeAllItems();
            while (res.next()) {
                cb_tanaman.addItem(res.getString("nama"));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        // data distributor
        try {
            String sql = "SELECT DISTINCT(Nama) as 'nama' FROM `tb_distributor`";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            cb_distributor.removeAllItems();
            while (res.next()) {
                cb_distributor.addItem(res.getString("nama"));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        // data admin
        try {
            String sql = "SELECT DISTINCT(Nama) as 'nama' FROM `tb_admin`";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            cb_admin.removeAllItems();
            while (res.next()) {
                cb_admin.addItem(res.getString("Nama"));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    private void getDataTransaksi() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        String sql = "select * from detail_transaksi";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[8];
                o[0] = res.getString("ID_penjualan");
                o[1] = res.getString("Kode_Tanaman");
                o[2] = res.getString("ID_Distributor");
                o[3] = res.getString("ID_Admin");
                o[4] = res.getString("Jumlah");
                o[5] = res.getString("Harga");
                o[6] = res.getString("Total");
                o[7] = res.getString("tgl_transaksi");
                model.addRow(o);
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_kode_tanaman = new javax.swing.JTextField();
        txt_id_distributor = new javax.swing.JTextField();
        txt_id_admin = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nomor_transaksi = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_total_harga = new javax.swing.JTextField();
        cb_tanaman = new javax.swing.JComboBox<>();
        cb_distributor = new javax.swing.JComboBox<>();
        cb_admin = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lbl_harga = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_stok_tanaman = new javax.swing.JLabel();
        dc_tanggal_transaksi = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transaksi = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(212, 228, 178));

        jPanel3.setBackground(new java.awt.Color(212, 228, 178));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TRANSAKSI PENJUALAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(212, 228, 178));

        jLabel2.setText("Nomor Transaksi");

        jLabel3.setText("Tanaman");

        jLabel4.setText("Distributor");

        jLabel5.setText("Admin");

        jLabel6.setText("Jumlah");

        jLabel7.setText("Total Harga");

        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });

        txt_total_harga.setEditable(false);

        cb_tanaman.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_tanamanPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cb_distributor.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_distributorPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cb_admin.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_adminPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("x");

        lbl_harga.setText("-");

        jLabel9.setText("Tanggal Transaksi");

        jLabel10.setText("Stok :");

        lbl_stok_tanaman.setText("-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(59, 59, 59)
                        .addComponent(txt_nomor_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dc_tanggal_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_total_harga, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(cb_tanaman, 0, 161, Short.MAX_VALUE)
                                .addComponent(cb_distributor, 0, 161, Short.MAX_VALUE)
                                .addComponent(cb_admin, 0, 161, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_harga))))))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_stok_tanaman, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nomor_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_tanaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_stok_tanaman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_distributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_harga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dc_tanggal_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbl_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_transaksi);

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addComponent(btn_kembali)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_ubah)
                    .addComponent(btn_hapus)
                    .addComponent(btn_refresh)
                    .addComponent(btn_print))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_kembali)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO `detail_transaksi`(`ID_Penjualan`, `Kode_Tanaman`, `ID_Distributor`, "
                    + "`ID_Admin`, `Jumlah`, `Harga`, `total`, `tgl_transaksi`) "
                    + "VALUES (?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_nomor_transaksi.getText());
            pst.setInt(2, Integer.parseInt(txt_kode_tanaman.getText()));
            pst.setInt(3, Integer.parseInt(txt_id_distributor.getText()));
            pst.setInt(4, Integer.parseInt(txt_id_admin.getText()));
            pst.setInt(5, Integer.parseInt(txt_jumlah.getText()));
            pst.setInt(6, Integer.parseInt(lbl_harga.getText()));
            pst.setInt(7, Integer.parseInt(txt_total_harga.getText()));
            SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date d = new java.util.Date();
            tgl_transaksi = date.format(d);
            pst.setString(8, tgl_transaksi);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Tambah Data transaksi berhasil");
            getDataTransaksi();
            btn_refreshActionPerformed(evt);
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Tambah Data transaksi gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void cb_tanamanPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_tanamanPopupMenuWillBecomeInvisible
        // menampung ID tanaman
        try {
            String sql = "select * from tb_tanaman where Nama='" + cb_tanaman.getSelectedItem().toString() + "'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                txt_kode_tanaman.setText(res.getString("Kode_Tanaman"));
                lbl_stok_tanaman.setText(res.getString("Tersedia"));
                System.out.println(txt_kode_tanaman.getText());

                // menampilkan harga tanaman 
                int harga = Integer.parseInt(res.getString("Harga"));
                lbl_harga.setText(String.valueOf(harga));
            }
        } catch (NumberFormatException | SQLException e) {
        }
    }//GEN-LAST:event_cb_tanamanPopupMenuWillBecomeInvisible

    private void cb_distributorPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_distributorPopupMenuWillBecomeInvisible
        // menampung ID Distributor
        try {
            String sql = "select * from tb_distributor where Nama='" + cb_distributor.getSelectedItem().toString() + "'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                txt_id_distributor.setText(res.getString("ID_Distributor"));
                System.out.println(txt_id_distributor.getText());
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_cb_distributorPopupMenuWillBecomeInvisible

    private void cb_adminPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_adminPopupMenuWillBecomeInvisible
        // menampung ID Admin
        try {
            String sql = "select * from tb_admin where Nama='" + cb_admin.getSelectedItem().toString() + "'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                txt_id_admin.setText(res.getString("ID_Admin"));
                System.out.println(txt_id_admin.getText());
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_cb_adminPopupMenuWillBecomeInvisible

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        txt_id_admin.setText("");
        txt_id_distributor.setText("");
        txt_kode_tanaman.setText("");
        txt_nomor_transaksi.setText("");
        txt_jumlah.setText("");
        txt_total_harga.setText("");
        lbl_harga.setText("");
        cb_admin.setSelectedIndex(0);
        cb_distributor.setSelectedIndex(0);
        cb_tanaman.setSelectedIndex(0);
        getDataTransaksi();
        dc_tanggal_transaksi.setCalendar(null);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        // Menghitung total harga
        if (txt_jumlah.getText().length() == 0) {
            txt_total_harga.setText("0");
        } else {
            if (Integer.parseInt(txt_jumlah.getText()) > Integer.parseInt(lbl_stok_tanaman.getText())) {
                JOptionPane.showMessageDialog(this, "Ketersediaan tanaman tidak cukup");
                txt_jumlah.setText("");
            } else {
                int total = Integer.parseInt(txt_jumlah.getText()) * Integer.parseInt(lbl_harga.getText());
                txt_total_harga.setText(String.valueOf(total));
            }
        }
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void tbl_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_transaksiMouseClicked

        try {

            // TODO add your handling code here:
            int i = tbl_transaksi.getSelectedRow();
            txt_nomor_transaksi.setText(model.getValueAt(i, 0).toString());
            kod_tanaman = Integer.parseInt(model.getValueAt(i, 1).toString());
            id_distributor = Integer.parseInt(model.getValueAt(i, 2).toString());
            id_admin = Integer.parseInt(model.getValueAt(i, 3).toString());
            try {
                String sql = "select * from tb_tanaman where Kode_Tanaman='" + kod_tanaman + "'";
                stat = conn.createStatement();
                res = stat.executeQuery(sql);
                if (res.next()) {
                    cb_tanaman.setSelectedItem(res.getString("Nama"));
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            try {
                String sql = "select * from tb_distributor where ID_Distributor='" + id_distributor + "'";
                stat = conn.createStatement();
                res = stat.executeQuery(sql);
                if (res.next()) {
                    cb_distributor.setSelectedItem(res.getString("Nama"));
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            try {
                String sql = "select * from tb_admin where ID_Admin='" + id_admin + "'";
                stat = conn.createStatement();
                res = stat.executeQuery(sql);
                if (res.next()) {
                    cb_admin.setSelectedItem(res.getString("Nama"));
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            txt_jumlah.setText(model.getValueAt(i, 4).toString());
            lbl_harga.setText(model.getValueAt(i, 5).toString());
            txt_total_harga.setText(model.getValueAt(i, 6).toString());
            java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(String.valueOf(model.getValueAt(i, 7)));
            dc_tanggal_transaksi.setDate(date);
            System.out.println(kod_tanaman);
            System.out.println(id_distributor);
            System.out.println(id_admin);
            System.out.println(kod_tanaman);
        } catch (ParseException ex) {
            Logger.getLogger(Form_Penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl_transaksiMouseClicked

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update `detail_transaksi` set `Kode_Tanaman`=?, `ID_Distributor`=?, "
                    + "`ID_Admin`=?, `Jumlah`=?, `Harga`=?, `total`=?, `tgl_transaksi`=? "
                    + "WHERE `ID_Penjualan`=?";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(txt_kode_tanaman.getText()));
            pst.setInt(2, Integer.parseInt(txt_id_distributor.getText()));
            pst.setInt(3, Integer.parseInt(txt_id_admin.getText()));
            pst.setInt(4, Integer.parseInt(txt_jumlah.getText()));
            pst.setInt(5, Integer.parseInt(lbl_harga.getText()));
            pst.setInt(6, Integer.parseInt(txt_total_harga.getText()));
            SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date d = new java.util.Date();
            tgl_transaksi = date.format(d);
            pst.setString(7, tgl_transaksi);
            pst.setString(8, txt_nomor_transaksi.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "Update Data transaksi berhasil");
            getDataTransaksi();
            btn_refreshActionPerformed(evt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Update Data transaksi gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from detail_transaksi where ID_Penjualan=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_nomor_transaksi.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "Hapus data berhasil");
            btn_refreshActionPerformed(evt);
            getDataTransaksi();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hapus data gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("laporanTransaksi.jasper"), null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        new MenuBaru().show();
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Form_Penjualan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> cb_admin;
    private javax.swing.JComboBox<String> cb_distributor;
    private javax.swing.JComboBox<String> cb_tanaman;
    private com.toedter.calendar.JDateChooser dc_tanggal_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_harga;
    private javax.swing.JLabel lbl_stok_tanaman;
    private javax.swing.JTable tbl_transaksi;
    private javax.swing.JTextField txt_id_admin;
    private javax.swing.JTextField txt_id_distributor;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kode_tanaman;
    private javax.swing.JTextField txt_nomor_transaksi;
    private javax.swing.JTextField txt_total_harga;
    // End of variables declaration//GEN-END:variables
}
