/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db_pertanian;

/**
 *
 * @author ibnua
 */
public class MenuBaru extends javax.swing.JFrame {

    /**
     * Creates new form MenuBaru
     */
    public MenuBaru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_admin = new javax.swing.JButton();
        btn_distributor = new javax.swing.JButton();
        btn_penjualan = new javax.swing.JButton();
        btn_tanaman = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_admin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_admin.setText("DATA ADMIN");
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 137, 30));

        btn_distributor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_distributor.setText("DISTRIBUTOR");
        btn_distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_distributorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_distributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 137, 30));

        btn_penjualan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_penjualan.setText("PENJUALAN");
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 140, 30));

        btn_tanaman.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_tanaman.setText("TANAMAN");
        btn_tanaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tanamanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 129, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_pertanian/brokoli.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 160, 160));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU UTAMA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 563, 66));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_pertanian/kiwi.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jPanel1.setBackground(new java.awt.Color(212, 228, 178));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_pertanian/jeruk.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 332, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_pertanian/markisa.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        // TODO add your handling code here:
        new Form_Admin().show();
        this.dispose();
    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_tanamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tanamanActionPerformed
        // TODO add your handling code here:
        new Form_Tanaman().show();
        this.dispose();
    }//GEN-LAST:event_btn_tanamanActionPerformed

    private void btn_distributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_distributorActionPerformed
        // TODO add your handling code here:
        new Form_Distributor().show();
        this.dispose();
    }//GEN-LAST:event_btn_distributorActionPerformed

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        // TODO add your handling code here:
        new Form_Penjualan().show();
        this.dispose();
    }//GEN-LAST:event_btn_penjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_distributor;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_tanaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
